

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: smallthings_db
      TZ: Asia/Jakarta
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./SEED_DATA.sql:/docker-entrypoint-initdb.d/SEED_DATA.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://root:password123@db:5432/smallthings_db?sslmode=disable
      - JWT_SECRET=super-secret-dev-key-change-in-prod
      - CORS_ORIGIN=http://localhost:3000
      - PORT=8080
      - GOOGLE_CLIENT_ID=112899621345-lfles6vamavj2ouc3b6todsidq6jgivn.apps.googleusercontent.com
      - BYPASS_TIME_CHECK=true
      - TZ=Asia/Jakarta
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://backend:8080
        NEXT_PUBLIC_SITE_URL: https://homotaxic-suspensefully-marvin.ngrok-free.dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
      - NEXT_PUBLIC_SITE_URL=https://homotaxic-suspensefully-marvin.ngrok-free.dev
      - TZ=Asia/Jakarta
    depends_on:
      - backend

volumes:
  pgdata:
